### ISSUE TITLE
Disable parent

### ISSUE THREAD

**Issue by eiadxp** [sourcechord/Lighty#1]
Thanks for the great library with a nice idea..... The only problem is that focus moves around through the underlying controls even if the dialog is displayed!!! FOCUS SHOULD BE KEPT IN THE DIALOG LAYER.

**Comment by sourcechord** [comment]
Hi, @eiadxp!

Thanks, for your feedback.
And sorry for replying so late.

I've fix this issue, and released Light v0.3.1
Now, Background layer is disabled when dialog is shown.
Please try it.

**Comment by eiadxp** [comment]
Looks great now..... Thank you
